apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tekton-pipeline-release.yaml
  - tekton-triggers-release.yaml
  - tekton-dashboard-release.yaml
  - tekton-dashboard-ing.yaml
  - https://raw.githubusercontent.com/tektoncd/catalog/master/task/kaniko/0.1/kaniko.yaml
  - pipeline-task-git-clone.yaml
  - pipeline-task-update-image.yaml
  - pipeline.yaml
  - pipeline-sa.yaml
  - pipeline-pvc.yaml
